jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: 
            sudo apt-get --allow update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install && npm run build
      - run: aws s3 sync build s3://circleci-mydas-test

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy