version: 2.1
jobs:
  build_deploy:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm install && npm run build
      - run: aws s3 sync build s3://circleci-mydas-test

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy